changelog:
  exclude:
    labels:
      - changelog-ignore
  categories:
    - title: "Enhancements :rocket:"
      labels:
        - enhancement
    - title: "Bug fixes :lady_beetle:"
      labels:
        - bug
    - title: "Other changes :shrug:"
      labels:
        - "*"
