project_id": "your-project-id"
"api_token": "your-api-token"
"base_path": "your-project-base-path"

"files": [
  {
    "source": "/path/to/your/source/files",
    "translation": "/path/to/translations/%two_letters_code%/%original_file_name%",
    "languages_mapping": {
      "two_letters_code": {
        "ko": "ko",  # Korean
        "en": "en",  # English
        "ru": "ru"   # Russian
      }
    }
  }
]
