[versions]
kotlin = "2.0.21"
appcompat = "1.7.0"
constraintLayout = "2.1.4"
material = "1.12.0"

[libraries]
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
materialComponents = { module = "com.google.android.material:material", version.ref = "material" }

[bundles]
androidx = ["kotlinStdlib", "appcompat", "constraintLayout", "materialComponents"]
